version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  tests:
    build: .
    command: pytest
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: transaction_xerpa.settings

volumes:
  postgres_data:
